<?php

namespace App\Http\Controllers\Portal;

use App\Http\Controllers\Controller;
use App\Models\ActivityLog;
use App\Models\Site;
use App\Models\SitePlugin;
use App\Traits\ApiResponse;
use Carbon\Carbon;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    use ApiResponse;

    /**
     * GET /api/dashboard/stats
     * Returns aggregated dashboard statistics.
     */
    public function stats(Request $request)
    {
        $user = $request->user();

        // Base query scoped by user access
        $sitesQuery = Site::accessibleBy($user);

        $totalSites = (clone $sitesQuery)->count();
        $onlineSites = (clone $sitesQuery)->where('status', 'connected')->count();
        $offlineSites = (clone $sitesQuery)->where('status', 'disconnected')->count();

        // Sites created this month
        $sitesThisMonth = (clone $sitesQuery)
            ->where('created_at', '>=', Carbon::now()->startOfMonth())
            ->count();

        // Plugin updates pending: count site_plugins where installed < latest
        $pluginUpdatesQuery = SitePlugin::whereHas('site', function ($q) use ($user) {
            $q->accessibleBy($user);
        })
            ->whereNotNull('installed_version')
            ->whereNotNull('latest_version')
            ->whereColumn('installed_version', '!=', 'latest_version');

        $pluginUpdatesPending = (clone $pluginUpdatesQuery)->count();
        $sitesWithUpdates = (clone $pluginUpdatesQuery)->distinct('site_id')->count('site_id');

        // Recent sites (top 5) with hosting name and last ping
        $recentSites = (clone $sitesQuery)
            ->with('hosting:id,name')
            ->select('id', 'name', 'url', 'status', 'hosting_id', 'last_ping_at', 'created_at')
            ->orderByDesc('last_ping_at')
            ->limit(5)
            ->get()
            ->map(function ($site) {
                return [
                    'id' => $site->id,
                    'name' => $site->name,
                    'url' => $site->url,
                    'status' => $site->status,
                    'hosting_name' => $site->hosting?->name ?? 'No hosting',
                    'last_seen_at' => $site->last_ping_at?->toIso8601String(),
                ];
            });

        // Recent activity logs (top 5)
        $recentActivity = ActivityLog::with('user:id,name')
            ->orderByDesc('created_at')
            ->limit(5)
            ->get()
            ->map(function ($log) {
                return [
                    'id' => $log->id,
                    'action' => $log->action,
                    'subject_type' => class_basename($log->subject_type ?? ''),
                    'subject_id' => $log->subject_id,
                    'description' => $this->formatActivityDescription($log),
                    'user_name' => $log->user?->name ?? 'System',
                    'created_at' => $log->created_at?->toIso8601String(),
                    'metadata' => $log->metadata,
                ];
            });

        return $this->successResponse([
            'total_sites' => $totalSites,
            'online_sites' => $onlineSites,
            'offline_sites' => $offlineSites,
            'sites_this_month' => $sitesThisMonth,
            'plugin_updates_pending' => $pluginUpdatesPending,
            'sites_with_updates' => $sitesWithUpdates,
            'recent_sites' => $recentSites,
            'recent_activity' => $recentActivity,
        ]);
    }

    /**
     * Format activity log into human-readable description.
     */
    private function formatActivityDescription(ActivityLog $log): string
    {
        $action = $log->action;
        $meta = $log->metadata ?? [];
        $userName = $log->user?->name ?? 'System';

        return match (true) {
            str_contains($action, 'site.created') => "Site created by {$userName}",
            str_contains($action, 'site.updated') => "Site updated by {$userName}",
            str_contains($action, 'site.deleted') => "Site deleted by {$userName}",
            str_contains($action, 'site.connected') => "Site connected",
            str_contains($action, 'site.disconnected') => "Site went offline",
            str_contains($action, 'site.api_key_regenerated') => "API key regenerated by {$userName}",
            str_contains($action, 'deployment') => "Plugin deployed by {$userName}",
            str_contains($action, 'plugin.created') => "Plugin created by {$userName}",
            str_contains($action, 'plugin.updated') => "Plugin updated by {$userName}",
            str_contains($action, 'version.uploaded') => "New version uploaded by {$userName}",
            str_contains($action, 'user.created') => "User created by {$userName}",
            str_contains($action, 'user.updated') => "User updated by {$userName}",
            str_contains($action, 'ping') => "Site pinged",
            default => "{$action} by {$userName}",
        };
    }
}
