<?php

namespace App\Services;

use App\Models\ActivityLog;

/**
 * Turns an ActivityLog row into a frontend-friendly payload (relative time
 * label is left to the FE; we just produce a human-readable `description`
 * plus normalized scalar fields).
 *
 * Lives in its own class so the Dashboard "recent activity" widget and the
 * /activity-logs page produce identical output — and so the human labels
 * are versioned in a single place when we add new action keys.
 */
class ActivityLogPresenter
{
    /**
     * Convert a single ActivityLog instance into the payload shape the
     * frontend expects. Caller is responsible for eager-loading `user` to
     * avoid N+1 ("with('user:id,name')" is the established pattern).
     */
    public static function present(ActivityLog $log): array
    {
        return [
            'id'           => $log->id,
            'action'       => $log->action,
            'subject_type' => class_basename($log->subject_type ?? ''),
            'subject_id'   => $log->subject_id,
            'description'  => self::describe($log),
            'user_id'      => $log->user_id,
            'user_name'    => $log->user?->name ?? 'System',
            'ip_address'   => $log->ip_address,
            'created_at'   => $log->created_at?->toIso8601String(),
            'metadata'     => $log->metadata,
        ];
    }

    /**
     * Human-readable label for the activity. Pattern matches DashboardController's
     * existing formatActivityDescription() — adding new actions here is the
     * canonical place to centralise that mapping.
     */
    public static function describe(ActivityLog $log): string
    {
        $action = $log->action;
        $userName = $log->user?->name ?? 'System';

        return match (true) {
            $action === 'site.created'                  => "Site created by {$userName}",
            $action === 'site.updated'                  => "Site updated by {$userName}",
            $action === 'site.deleted'                  => "Site deleted by {$userName}",
            $action === 'site.restored'                 => "Site restored by {$userName}",
            $action === 'site.connected'                => "Site connected",
            $action === 'site.disconnected'             => "Site went offline",
            $action === 'site.recovered'                => "Site recovered (reconnected)",
            $action === 'site.api_key_regenerated'      => "API key regenerated by {$userName}",
            $action === 'site.sync_now'                 => "Manual sync triggered by {$userName}",
            str_starts_with($action, 'deployment')      => "Deployment action by {$userName}",
            $action === 'plugin.created'                => "Plugin created by {$userName}",
            $action === 'plugin.updated'                => "Plugin updated by {$userName}",
            $action === 'version.uploaded'              => "New plugin version uploaded by {$userName}",
            $action === 'user.created'                  => "User created by {$userName}",
            $action === 'user.updated'                  => "User updated by {$userName}",
            $action === 'user.deleted'                  => "User deleted by {$userName}",
            $action === 'user.role_changed'             => "User role changed by {$userName}",
            $action === 'hosting.created'               => "Hosting created by {$userName}",
            $action === 'hosting.updated'               => "Hosting updated by {$userName}",
            $action === 'hosting.deleted'               => "Hosting deleted by {$userName}",
            str_contains($action, 'ping')               => "Site pinged",
            default                                     => "{$action} by {$userName}",
        };
    }
}
